version: "3"
services:
  jmusicbot:
    container_name: jmusicbot
    environment:
      - APP_ENV=docker
    image: nfxus/jmusicbot:latest
    network_mode: bridge
    restart: always
    volumes:
      - /opt/jmusicbot:/usr/src/musicbot
      - /opt/jmusicbot/serversettings.json:/usr/src/musicbot/serversettings.json
